In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('/content/teleCust1000t.csv')

In [3]:
data.head()

,region,tenure,age,marital,address,income,ed,employ,retire,gender,reside,custcat
0,2,13,44,1,9,64.0,4,5,0.0,0,2,1
1,3,11,33,1,7,136.0,5,5,0.0,0,6,4
2,3,68,52,1,24,116.0,1,29,0.0,1,2,3
3,2,33,33,0,12,33.0,2,0,0.0,1,1,1
4,2,23,30,1,9,30.0,1,2,0.0,0,4,3

In [4]:
data.shape

(1000, 12)

In [5]:
data['custcat'].value_counts()

custcat
3    281
1    266
4    236
2    217
Name: count, dtype: int64

In [6]:
data.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   region   1000 non-null   int64
 1   tenure   1000 non-null   int64
 2   age      1000 non-null   int64
 3   marital  1000 non-null   int64
 4   address  1000 non-null   int64
 5   income   1000 non-null   float64
 6   ed       1000 non-null   int64
 7   employ   1000 non-null   int64
 8   retire   1000 non-null   float64
 9   gender   1000 non-null   int64
 10  reside   1000 non-null   int64
 11  custcat  1000 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 93.9 KB

In [8]:
data

,region,tenure,age,marital,address,income,ed,employ,retire,gender,reside,custcat
0,2,13,44,1,9,64.0,4,5,0.0,0,2,1
1,3,11,33,1,7,136.0,5,5,0.0,0,6,4
2,3,68,52,1,24,116.0,1,29,0.0,1,2,3
3,2,33,33,0,12,33.0,2,0,0.0,1,1,1
4,2,23,30,1,9,30.0,1,2,0.0,0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,10,39,0,0,27.0,3,0,0.0,1,3,1
996,1,7,34,0,2,22.0,5,5,0.0,1,1,1
997,3,67,59,0,40,944.0,5,33,0.0,1,1,4
998,3,70,49,0,18,87.0,2,22,0.0,1,1,3
999,3,50,36,1,7,39.0,3,3,0.0,1,3,2

In [9]:
x = data.drop('custcat',axis=1)
y = data['custcat']

In [10]:
x

,region,tenure,age,marital,address,income,ed,employ,retire,gender,reside
0,2,13,44,1,9,64.0,4,5,0.0,0,2
1,3,11,33,1,7,136.0,5,5,0.0,0,6
2,3,68,52,1,24,116.0,1,29,0.0,1,2
3,2,33,33,0,12,33.0,2,0,0.0,1,1
4,2,23,30,1,9,30.0,1,2,0.0,0,4
...,...,...,...,...,...,...,...,...,...,...,...
995,3,10,39,0,0,27.0,3,0,0.0,1,3
996,1,7,34,0,2,22.0,5,5,0.0,1,1
997,3,67,59,0,40,944.0,5,33,0.0,1,1
998,3,70,49,0,18,87.0,2,22,0.0,1,1
999,3,50,36,1,7,39.0,3,3,0.0,1,3

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [15]:
x

array([[-0.02696767, -1.055125  ,  0.18450456, ..., -0.22207644,
        -1.03459817, -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243, ..., -0.22207644,
        -1.03459817,  2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601, ..., -0.22207644,
         0.96655883, -0.23065004],
       ...,
       [ 1.19883553,  1.47425216,  1.37948227, ..., -0.22207644,
         0.96655883, -0.92747794],
       [ 1.19883553,  1.61477311,  0.58283046, ..., -0.22207644,
         0.96655883, -0.92747794],
       [ 1.19883553,  0.67796676, -0.45281689, ..., -0.22207644,
         0.96655883,  0.46617787]])

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 11)
(200, 11)
(800,)
(200,)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
kc = KNeighborsClassifier()

In [20]:
kc.fit(x_train,y_train)

KNeighborsClassifier()

In [21]:
predict = kc.predict(x_test)

In [22]:
predict

array([3, 1, 2, 2, 2, 1, 3, 1, 3, 1, 2, 1, 3, 2, 1, 2, 1, 1, 1, 3, 2, 1,
       4, 2, 1, 1, 4, 3, 2, 1, 1, 2, 3, 4, 1, 3, 1, 4, 3, 1, 1, 1, 1, 3,
       3, 4, 1, 3, 1, 1, 3, 3, 2, 2, 2, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 1,
       4, 1, 4, 1, 2, 3, 3, 2, 2, 4, 2, 2, 3, 1, 1, 1, 4, 1, 3, 3, 2, 1,
       2, 1, 3, 2, 2, 1, 4, 3, 2, 1, 2, 1, 2, 3, 3, 4, 1, 4, 2, 4, 3, 2,
       2, 3, 4, 1, 1, 2, 1, 2, 3, 3, 1, 1, 3, 3, 3, 1, 2, 4, 1, 3, 4, 2,
       4, 3, 2, 2, 1, 3, 4, 1, 2, 1, 4, 4, 2, 2, 2, 4, 2, 3, 2, 1, 2, 4,
       3, 2, 1, 2, 3, 1, 1, 4, 1, 2, 3, 2, 1, 3, 3, 1, 4, 3, 4, 1, 3, 3,
       3, 2, 2, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3, 4, 1, 4, 2, 2, 3, 1, 1, 2,
       3, 2])

In [28]:
from sklearn.metrics import accuracy_score
print("training_accuray: ",accuracy_score(y_train,kc.predict(x_train)))
print("test_accuracy: ",accuracy_score(y_test,predict))

training_accuray:  0.5625
test_accuracy:  0.32